version: "3.10"

services:
  web_itvpn_analys:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_itvpn_analys
    restart: always
    command: >
      sh -c "python time.py
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py datavpn
      && python manage.py runserver 0.0.0.0:8000
      && python manage.py crontab add"
#      && celery -A BACKVPN  beat -l INFO
#      && celery -A BACKVPN  worker --loglevel=INFO --concurrency 1 -P solo


    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    environment:
      - SQL_HOST=db
      - SQL_USER=postgres
      - SQL_NAME=x1
      - POSTGRES_PASSWORD=1111
    depends_on:
      - db
  db:
    restart: always
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=1111
    image: postgres:latest
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    container_name: vpn_analys_db

  redis:
    image: redis:alpine
    depends_on:
      - db

volumes:
  postgres_data: