version: "3"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=2278
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    #      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web_it:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web
    command: >
      sh -c "python time.py
      && python manage.py makemigrations 
      && python manage.py migrate 
      && python manage.py datapp 
      && python manage.py runserver 0.0.0.0:800
      &&  celery -A x1Lubeshko beat"

    volumes:
      - ./:/usr/src/app
    environment:
      - SQL_HOST=postgresdb
      - SQL_USER=postgres
      - SQL_NAME=acountdb
      - POSTGRES_PASSWORD=2278
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"

#  nginx:
#    build:
#      context: ./docker/nginx
#      dockerfile: Dockerfile
#    depends_on:
#      - web_it
#      - postgresdb
#    ports:
#      - "80:80"
#
#    volumes:
#      - ./static/:/static
volumes:
  postgres_data:




